=== t-oninon/Optimizing-sensor-network-coverage-with-genetic-algorithm/src/cga/data/sensor.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT SensorProblem (Sensors,Hotspots)>
<!ELEMENT Sensors (Sensor+)>
<!ELEMENT Sensor (#PCDATA)>
<!ELEMENT Hotspots (Hotspot*)>
<!ELEMENT Hotspot (#PCDATA)>

<!ATTLIST SensorProblem areaWidth CDATA #REQUIRED>
<!ATTLIST SensorProblem areaHeight CDATA #REQUIRED>
<!ATTLIST Sensors radius CDATA #REQUIRED>
<!ATTLIST Sensor x CDATA #REQUIRED>
<!ATTLIST Sensor y CDATA #REQUIRED>
<!ATTLIST Hotspots kCovered CDATA #REQUIRED>
<!ATTLIST Hotspot x CDATA #REQUIRED>
<!ATTLIST Hotspot y CDATA #REQUIRED>

=== t-oninon/Optimizing-sensor-network-coverage-with-genetic-algorithm/sensorler2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sensor SYSTEM "src/cga/data/sensor.dtd">
<SensorProblem areaWidth="400" areaHeight="400">
	<Sensors radius="50">
		<Sensor x="400" y="400" />
		<Sensor x="200" y="200" />
		<Sensor x="100" y="100" />
		<Sensor x="400" y="400" />
		<Sensor x="200" y="200" />
		<Sensor x="100" y="100" />
		<Sensor x="400" y="400" />
		<Sensor x="200" y="200" />
		<Sensor x="100" y="100" />
		<Sensor x="150" y="150" />
		<Sensor x="150" y="150" />
		<Sensor x="150" y="150" />
	</Sensors>
	<Hotspots kCovered="1">
		<Hotspot x="400" y="400" />
		<Hotspot x="200" y="200" />
		<Hotspot x="100" y="100" />
	</Hotspots>
</SensorProblem>
